{% set name = "proxsuite" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: da784a9eb9298f8660744280fe4e4ed421098c3c00682badafea5962fb4c895a

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - clang  # [win]
    - make  # [not win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - simde
    - doxygen
  host:
    - eigen
    - python
    - simde
  run:
    - eigen
    - python
    - scipy
    - numpy
    - simde

test:
  imports:
    - proxsuite
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/simple-robotics/proxsuite
  summary: Quadratic Programming Solver for Robotics and beyond.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/simple-robotics/proxsuite

extra:
  recipe-maintainers:
    - jorisv
    - fabinsch
    - jcarpent
    - Bambade
