{% set name = "proxsuite" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb90a9e45f5bf91659c394b7cfa22f9754bd864798c10a1269d342f6a456a1f3

  patches:
    # Add ABI tag https://github.com/Simple-Robotics/proxsuite/pull/321
    - patches/0001-python-Add-Python-ABI-tag-mandatory-for-pypy.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - clang  # [win]
    - make  # [not win]
    - doxygen
  host:
    - eigen
    - python
    - simde
  run:
    - eigen
    - python
    - scipy
    - numpy
    - simde

test:
  imports:
    - proxsuite
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/simple-robotics/proxsuite
  summary: Quadratic Programming Solver for Robotics and beyond.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/simple-robotics/proxsuite

extra:
  recipe-maintainers:
    - jorisv
    - fabinsch
    - jcarpent
    - Bambade
