{% set name = "proxsuite" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c7f89d2c7a52e157ba5fb20ff2a73117574d7ec629a11f9c5f05b549c59bf7b

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - clang  # [win]
    - make  # [not win]
    - doxygen
    - libgomp       # [linux]
    - llvm-openmp   # [osx or win]
  host:
    - eigen
    - python
    - simde
  run:
    - eigen
    - python
    - scipy
    - numpy
    - simde

test:
  imports:
    - proxsuite
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/simple-robotics/proxsuite
  summary: Quadratic Programming Solver for Robotics and beyond.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/simple-robotics/proxsuite

extra:
  recipe-maintainers:
    - jorisv
    - fabinsch
    - jcarpent
    - Bambade
